export * from './animal.service';
import { AnimalService } from './animal.service';
export * from './astronomicalObject.service';
import { AstronomicalObjectService } from './astronomicalObject.service';
export * from './book.service';
import { BookService } from './book.service';
export * from './bookCollection.service';
import { BookCollectionService } from './bookCollection.service';
export * from './bookSeries.service';
import { BookSeriesService } from './bookSeries.service';
export * from './character.service';
import { CharacterService } from './character.service';
export * from './comicCollection.service';
import { ComicCollectionService } from './comicCollection.service';
export * from './comicSeries.service';
import { ComicSeriesService } from './comicSeries.service';
export * from './comicStrip.service';
import { ComicStripService } from './comicStrip.service';
export * from './comics.service';
import { ComicsService } from './comics.service';
export * from './company.service';
import { CompanyService } from './company.service';
export * from './conflict.service';
import { ConflictService } from './conflict.service';
export * from './dataVersion.service';
import { DataVersionService } from './dataVersion.service';
export * from './element.service';
import { ElementService } from './element.service';
export * from './episode.service';
import { EpisodeService } from './episode.service';
export * from './food.service';
import { FoodService } from './food.service';
export * from './literature.service';
import { LiteratureService } from './literature.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './magazine.service';
import { MagazineService } from './magazine.service';
export * from './magazineSeries.service';
import { MagazineSeriesService } from './magazineSeries.service';
export * from './material.service';
import { MaterialService } from './material.service';
export * from './medicalCondition.service';
import { MedicalConditionService } from './medicalCondition.service';
export * from './movie.service';
import { MovieService } from './movie.service';
export * from './occupation.service';
import { OccupationService } from './occupation.service';
export * from './organization.service';
import { OrganizationService } from './organization.service';
export * from './performer.service';
import { PerformerService } from './performer.service';
export * from './season.service';
import { SeasonService } from './season.service';
export * from './series.service';
import { SeriesService } from './series.service';
export * from './soundtrack.service';
import { SoundtrackService } from './soundtrack.service';
export * from './spacecraft.service';
import { SpacecraftService } from './spacecraft.service';
export * from './spacecraftClass.service';
import { SpacecraftClassService } from './spacecraftClass.service';
export * from './species.service';
import { SpeciesService } from './species.service';
export * from './staff.service';
import { StaffService } from './staff.service';
export * from './technology.service';
import { TechnologyService } from './technology.service';
export * from './title.service';
import { TitleService } from './title.service';
export * from './tradingCard.service';
import { TradingCardService } from './tradingCard.service';
export * from './tradingCardDeck.service';
import { TradingCardDeckService } from './tradingCardDeck.service';
export * from './tradingCardSet.service';
import { TradingCardSetService } from './tradingCardSet.service';
export * from './videoGame.service';
import { VideoGameService } from './videoGame.service';
export * from './videoRelease.service';
import { VideoReleaseService } from './videoRelease.service';
export * from './weapon.service';
import { WeaponService } from './weapon.service';
export const APIS = [AnimalService, AstronomicalObjectService, BookService, BookCollectionService, BookSeriesService, CharacterService, ComicCollectionService, ComicSeriesService, ComicStripService, ComicsService, CompanyService, ConflictService, DataVersionService, ElementService, EpisodeService, FoodService, LiteratureService, LocationService, MagazineService, MagazineSeriesService, MaterialService, MedicalConditionService, MovieService, OccupationService, OrganizationService, PerformerService, SeasonService, SeriesService, SoundtrackService, SpacecraftService, SpacecraftClassService, SpeciesService, StaffService, TechnologyService, TitleService, TradingCardService, TradingCardDeckService, TradingCardSetService, VideoGameService, VideoReleaseService, WeaponService];
