/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { BookBaseResponse } from '../model/bookBaseResponse';
import { BookFullResponse } from '../model/bookFullResponse';
import { BookV2BaseResponse } from '../model/bookV2BaseResponse';
import { BookV2FullResponse } from '../model/bookV2FullResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class BookService {

    protected basePath = 'https://stapi.co/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Retrieval of a single book
     * @param uid Book unique ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1GetBook(uid: string, observe?: 'body', reportProgress?: boolean): Observable<BookFullResponse>;
    public v1GetBook(uid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BookFullResponse>>;
    public v1GetBook(uid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BookFullResponse>>;
    public v1GetBook(uid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling v1GetBook.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (uid !== undefined && uid !== null) {
            queryParameters = queryParameters.set('uid', <any>uid);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<BookFullResponse>('get',`${this.basePath}/v1/rest/book`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Pagination over books
     * @param pageNumber Zero-based page number
     * @param pageSize Page size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1PageBooks(pageNumber?: number, pageSize?: number, observe?: 'body', reportProgress?: boolean): Observable<BookBaseResponse>;
    public v1PageBooks(pageNumber?: number, pageSize?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BookBaseResponse>>;
    public v1PageBooks(pageNumber?: number, pageSize?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BookBaseResponse>>;
    public v1PageBooks(pageNumber?: number, pageSize?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<BookBaseResponse>('get',`${this.basePath}/v1/rest/book/search`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Searching books
     * @param title 
     * @param publishedYearFrom 
     * @param publishedYearTo 
     * @param numberOfPagesFrom 
     * @param numberOfPagesTo 
     * @param stardateFrom 
     * @param stardateTo 
     * @param yearFrom 
     * @param yearTo 
     * @param novel 
     * @param referenceBook 
     * @param biographyBook 
     * @param rolePlayingBook 
     * @param eBook 
     * @param anthology 
     * @param novelization 
     * @param audiobook 
     * @param audiobookAbridged 
     * @param audiobookPublishedYearFrom 
     * @param audiobookPublishedYearTo 
     * @param audiobookRunTimeFrom 
     * @param audiobookRunTimeTo 
     * @param pageNumber Zero-based page number
     * @param pageSize Page size
     * @param sort Sorting, serialized like this: fieldName,ASC;anotherFieldName,DESC
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1SearchBooksForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfPagesFrom?: number, numberOfPagesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, novel?: boolean, referenceBook?: boolean, biographyBook?: boolean, rolePlayingBook?: boolean, eBook?: boolean, anthology?: boolean, novelization?: boolean, audiobook?: boolean, audiobookAbridged?: boolean, audiobookPublishedYearFrom?: number, audiobookPublishedYearTo?: number, audiobookRunTimeFrom?: number, audiobookRunTimeTo?: number, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'body', reportProgress?: boolean): Observable<BookBaseResponse>;
    public v1SearchBooksForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfPagesFrom?: number, numberOfPagesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, novel?: boolean, referenceBook?: boolean, biographyBook?: boolean, rolePlayingBook?: boolean, eBook?: boolean, anthology?: boolean, novelization?: boolean, audiobook?: boolean, audiobookAbridged?: boolean, audiobookPublishedYearFrom?: number, audiobookPublishedYearTo?: number, audiobookRunTimeFrom?: number, audiobookRunTimeTo?: number, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BookBaseResponse>>;
    public v1SearchBooksForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfPagesFrom?: number, numberOfPagesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, novel?: boolean, referenceBook?: boolean, biographyBook?: boolean, rolePlayingBook?: boolean, eBook?: boolean, anthology?: boolean, novelization?: boolean, audiobook?: boolean, audiobookAbridged?: boolean, audiobookPublishedYearFrom?: number, audiobookPublishedYearTo?: number, audiobookRunTimeFrom?: number, audiobookRunTimeTo?: number, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BookBaseResponse>>;
    public v1SearchBooksForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfPagesFrom?: number, numberOfPagesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, novel?: boolean, referenceBook?: boolean, biographyBook?: boolean, rolePlayingBook?: boolean, eBook?: boolean, anthology?: boolean, novelization?: boolean, audiobook?: boolean, audiobookAbridged?: boolean, audiobookPublishedYearFrom?: number, audiobookPublishedYearTo?: number, audiobookRunTimeFrom?: number, audiobookRunTimeTo?: number, pageNumber?: number, pageSize?: number, sort?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


























        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (title !== undefined) {
            formParams = formParams.append('title', <any>title) as any || formParams;
        }
        if (publishedYearFrom !== undefined) {
            formParams = formParams.append('publishedYearFrom', <any>publishedYearFrom) as any || formParams;
        }
        if (publishedYearTo !== undefined) {
            formParams = formParams.append('publishedYearTo', <any>publishedYearTo) as any || formParams;
        }
        if (numberOfPagesFrom !== undefined) {
            formParams = formParams.append('numberOfPagesFrom', <any>numberOfPagesFrom) as any || formParams;
        }
        if (numberOfPagesTo !== undefined) {
            formParams = formParams.append('numberOfPagesTo', <any>numberOfPagesTo) as any || formParams;
        }
        if (stardateFrom !== undefined) {
            formParams = formParams.append('stardateFrom', <any>stardateFrom) as any || formParams;
        }
        if (stardateTo !== undefined) {
            formParams = formParams.append('stardateTo', <any>stardateTo) as any || formParams;
        }
        if (yearFrom !== undefined) {
            formParams = formParams.append('yearFrom', <any>yearFrom) as any || formParams;
        }
        if (yearTo !== undefined) {
            formParams = formParams.append('yearTo', <any>yearTo) as any || formParams;
        }
        if (novel !== undefined) {
            formParams = formParams.append('novel', <any>novel) as any || formParams;
        }
        if (referenceBook !== undefined) {
            formParams = formParams.append('referenceBook', <any>referenceBook) as any || formParams;
        }
        if (biographyBook !== undefined) {
            formParams = formParams.append('biographyBook', <any>biographyBook) as any || formParams;
        }
        if (rolePlayingBook !== undefined) {
            formParams = formParams.append('rolePlayingBook', <any>rolePlayingBook) as any || formParams;
        }
        if (eBook !== undefined) {
            formParams = formParams.append('eBook', <any>eBook) as any || formParams;
        }
        if (anthology !== undefined) {
            formParams = formParams.append('anthology', <any>anthology) as any || formParams;
        }
        if (novelization !== undefined) {
            formParams = formParams.append('novelization', <any>novelization) as any || formParams;
        }
        if (audiobook !== undefined) {
            formParams = formParams.append('audiobook', <any>audiobook) as any || formParams;
        }
        if (audiobookAbridged !== undefined) {
            formParams = formParams.append('audiobookAbridged', <any>audiobookAbridged) as any || formParams;
        }
        if (audiobookPublishedYearFrom !== undefined) {
            formParams = formParams.append('audiobookPublishedYearFrom', <any>audiobookPublishedYearFrom) as any || formParams;
        }
        if (audiobookPublishedYearTo !== undefined) {
            formParams = formParams.append('audiobookPublishedYearTo', <any>audiobookPublishedYearTo) as any || formParams;
        }
        if (audiobookRunTimeFrom !== undefined) {
            formParams = formParams.append('audiobookRunTimeFrom', <any>audiobookRunTimeFrom) as any || formParams;
        }
        if (audiobookRunTimeTo !== undefined) {
            formParams = formParams.append('audiobookRunTimeTo', <any>audiobookRunTimeTo) as any || formParams;
        }

        return this.httpClient.request<BookBaseResponse>('post',`${this.basePath}/v1/rest/book/search`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Retrieval of a single book (V2)
     * @param uid Book unique ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2GetBook(uid: string, observe?: 'body', reportProgress?: boolean): Observable<BookV2FullResponse>;
    public v2GetBook(uid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BookV2FullResponse>>;
    public v2GetBook(uid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BookV2FullResponse>>;
    public v2GetBook(uid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling v2GetBook.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (uid !== undefined && uid !== null) {
            queryParameters = queryParameters.set('uid', <any>uid);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<BookV2FullResponse>('get',`${this.basePath}/v2/rest/book`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Pagination over books (V2)
     * @param pageNumber Zero-based page number
     * @param pageSize Page size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2PageBooks(pageNumber?: number, pageSize?: number, observe?: 'body', reportProgress?: boolean): Observable<BookV2BaseResponse>;
    public v2PageBooks(pageNumber?: number, pageSize?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BookV2BaseResponse>>;
    public v2PageBooks(pageNumber?: number, pageSize?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BookV2BaseResponse>>;
    public v2PageBooks(pageNumber?: number, pageSize?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<BookV2BaseResponse>('get',`${this.basePath}/v2/rest/book/search`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Searching books (V2)
     * @param title 
     * @param publishedYearFrom 
     * @param publishedYearTo 
     * @param numberOfPagesFrom 
     * @param numberOfPagesTo 
     * @param stardateFrom 
     * @param stardateTo 
     * @param yearFrom 
     * @param yearTo 
     * @param novel 
     * @param referenceBook 
     * @param biographyBook 
     * @param rolePlayingBook 
     * @param eBook 
     * @param anthology 
     * @param novelization 
     * @param unauthorizedPublication 
     * @param audiobook 
     * @param audiobookAbridged 
     * @param audiobookPublishedYearFrom 
     * @param audiobookPublishedYearTo 
     * @param audiobookRunTimeFrom 
     * @param audiobookRunTimeTo 
     * @param pageNumber Zero-based page number
     * @param pageSize Page size
     * @param sort Sorting, serialized like this: fieldName,ASC;anotherFieldName,DESC
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2SearchBooksForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfPagesFrom?: number, numberOfPagesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, novel?: boolean, referenceBook?: boolean, biographyBook?: boolean, rolePlayingBook?: boolean, eBook?: boolean, anthology?: boolean, novelization?: boolean, unauthorizedPublication?: boolean, audiobook?: boolean, audiobookAbridged?: boolean, audiobookPublishedYearFrom?: number, audiobookPublishedYearTo?: number, audiobookRunTimeFrom?: number, audiobookRunTimeTo?: number, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'body', reportProgress?: boolean): Observable<BookV2BaseResponse>;
    public v2SearchBooksForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfPagesFrom?: number, numberOfPagesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, novel?: boolean, referenceBook?: boolean, biographyBook?: boolean, rolePlayingBook?: boolean, eBook?: boolean, anthology?: boolean, novelization?: boolean, unauthorizedPublication?: boolean, audiobook?: boolean, audiobookAbridged?: boolean, audiobookPublishedYearFrom?: number, audiobookPublishedYearTo?: number, audiobookRunTimeFrom?: number, audiobookRunTimeTo?: number, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BookV2BaseResponse>>;
    public v2SearchBooksForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfPagesFrom?: number, numberOfPagesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, novel?: boolean, referenceBook?: boolean, biographyBook?: boolean, rolePlayingBook?: boolean, eBook?: boolean, anthology?: boolean, novelization?: boolean, unauthorizedPublication?: boolean, audiobook?: boolean, audiobookAbridged?: boolean, audiobookPublishedYearFrom?: number, audiobookPublishedYearTo?: number, audiobookRunTimeFrom?: number, audiobookRunTimeTo?: number, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BookV2BaseResponse>>;
    public v2SearchBooksForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfPagesFrom?: number, numberOfPagesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, novel?: boolean, referenceBook?: boolean, biographyBook?: boolean, rolePlayingBook?: boolean, eBook?: boolean, anthology?: boolean, novelization?: boolean, unauthorizedPublication?: boolean, audiobook?: boolean, audiobookAbridged?: boolean, audiobookPublishedYearFrom?: number, audiobookPublishedYearTo?: number, audiobookRunTimeFrom?: number, audiobookRunTimeTo?: number, pageNumber?: number, pageSize?: number, sort?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



























        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (title !== undefined) {
            formParams = formParams.append('title', <any>title) as any || formParams;
        }
        if (publishedYearFrom !== undefined) {
            formParams = formParams.append('publishedYearFrom', <any>publishedYearFrom) as any || formParams;
        }
        if (publishedYearTo !== undefined) {
            formParams = formParams.append('publishedYearTo', <any>publishedYearTo) as any || formParams;
        }
        if (numberOfPagesFrom !== undefined) {
            formParams = formParams.append('numberOfPagesFrom', <any>numberOfPagesFrom) as any || formParams;
        }
        if (numberOfPagesTo !== undefined) {
            formParams = formParams.append('numberOfPagesTo', <any>numberOfPagesTo) as any || formParams;
        }
        if (stardateFrom !== undefined) {
            formParams = formParams.append('stardateFrom', <any>stardateFrom) as any || formParams;
        }
        if (stardateTo !== undefined) {
            formParams = formParams.append('stardateTo', <any>stardateTo) as any || formParams;
        }
        if (yearFrom !== undefined) {
            formParams = formParams.append('yearFrom', <any>yearFrom) as any || formParams;
        }
        if (yearTo !== undefined) {
            formParams = formParams.append('yearTo', <any>yearTo) as any || formParams;
        }
        if (novel !== undefined) {
            formParams = formParams.append('novel', <any>novel) as any || formParams;
        }
        if (referenceBook !== undefined) {
            formParams = formParams.append('referenceBook', <any>referenceBook) as any || formParams;
        }
        if (biographyBook !== undefined) {
            formParams = formParams.append('biographyBook', <any>biographyBook) as any || formParams;
        }
        if (rolePlayingBook !== undefined) {
            formParams = formParams.append('rolePlayingBook', <any>rolePlayingBook) as any || formParams;
        }
        if (eBook !== undefined) {
            formParams = formParams.append('eBook', <any>eBook) as any || formParams;
        }
        if (anthology !== undefined) {
            formParams = formParams.append('anthology', <any>anthology) as any || formParams;
        }
        if (novelization !== undefined) {
            formParams = formParams.append('novelization', <any>novelization) as any || formParams;
        }
        if (unauthorizedPublication !== undefined) {
            formParams = formParams.append('unauthorizedPublication', <any>unauthorizedPublication) as any || formParams;
        }
        if (audiobook !== undefined) {
            formParams = formParams.append('audiobook', <any>audiobook) as any || formParams;
        }
        if (audiobookAbridged !== undefined) {
            formParams = formParams.append('audiobookAbridged', <any>audiobookAbridged) as any || formParams;
        }
        if (audiobookPublishedYearFrom !== undefined) {
            formParams = formParams.append('audiobookPublishedYearFrom', <any>audiobookPublishedYearFrom) as any || formParams;
        }
        if (audiobookPublishedYearTo !== undefined) {
            formParams = formParams.append('audiobookPublishedYearTo', <any>audiobookPublishedYearTo) as any || formParams;
        }
        if (audiobookRunTimeFrom !== undefined) {
            formParams = formParams.append('audiobookRunTimeFrom', <any>audiobookRunTimeFrom) as any || formParams;
        }
        if (audiobookRunTimeTo !== undefined) {
            formParams = formParams.append('audiobookRunTimeTo', <any>audiobookRunTimeTo) as any || formParams;
        }

        return this.httpClient.request<BookV2BaseResponse>('post',`${this.basePath}/v2/rest/book/search`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
