/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ComicSeriesBaseResponse } from '../model/comicSeriesBaseResponse';
import { ComicSeriesFullResponse } from '../model/comicSeriesFullResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ComicSeriesService {

    protected basePath = 'https://stapi.co/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Retrieval of a single comic series
     * @param uid Comic series unique ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1GetComicSeries(uid: string, observe?: 'body', reportProgress?: boolean): Observable<ComicSeriesFullResponse>;
    public v1GetComicSeries(uid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ComicSeriesFullResponse>>;
    public v1GetComicSeries(uid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ComicSeriesFullResponse>>;
    public v1GetComicSeries(uid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling v1GetComicSeries.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (uid !== undefined && uid !== null) {
            queryParameters = queryParameters.set('uid', <any>uid);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ComicSeriesFullResponse>('get',`${this.basePath}/v1/rest/comicSeries`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Pagination over comic series
     * @param pageNumber Zero-based page number
     * @param pageSize Page size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1PageComicSeries(pageNumber?: number, pageSize?: number, observe?: 'body', reportProgress?: boolean): Observable<ComicSeriesBaseResponse>;
    public v1PageComicSeries(pageNumber?: number, pageSize?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ComicSeriesBaseResponse>>;
    public v1PageComicSeries(pageNumber?: number, pageSize?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ComicSeriesBaseResponse>>;
    public v1PageComicSeries(pageNumber?: number, pageSize?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ComicSeriesBaseResponse>('get',`${this.basePath}/v1/rest/comicSeries/search`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Searching comic series
     * @param title 
     * @param publishedYearFrom 
     * @param publishedYearTo 
     * @param numberOfIssuesFrom 
     * @param numberOfIssuesTo 
     * @param stardateFrom 
     * @param stardateTo 
     * @param yearFrom 
     * @param yearTo 
     * @param miniseries 
     * @param photonovelSeries 
     * @param pageNumber Zero-based page number
     * @param pageSize Page size
     * @param sort Sorting, serialized like this: fieldName,ASC;anotherFieldName,DESC
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1SearchComicSeriesForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfIssuesFrom?: number, numberOfIssuesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, miniseries?: boolean, photonovelSeries?: boolean, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'body', reportProgress?: boolean): Observable<ComicSeriesBaseResponse>;
    public v1SearchComicSeriesForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfIssuesFrom?: number, numberOfIssuesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, miniseries?: boolean, photonovelSeries?: boolean, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ComicSeriesBaseResponse>>;
    public v1SearchComicSeriesForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfIssuesFrom?: number, numberOfIssuesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, miniseries?: boolean, photonovelSeries?: boolean, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ComicSeriesBaseResponse>>;
    public v1SearchComicSeriesForm(title?: string, publishedYearFrom?: number, publishedYearTo?: number, numberOfIssuesFrom?: number, numberOfIssuesTo?: number, stardateFrom?: number, stardateTo?: number, yearFrom?: number, yearTo?: number, miniseries?: boolean, photonovelSeries?: boolean, pageNumber?: number, pageSize?: number, sort?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {















        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (title !== undefined) {
            formParams = formParams.append('title', <any>title) as any || formParams;
        }
        if (publishedYearFrom !== undefined) {
            formParams = formParams.append('publishedYearFrom', <any>publishedYearFrom) as any || formParams;
        }
        if (publishedYearTo !== undefined) {
            formParams = formParams.append('publishedYearTo', <any>publishedYearTo) as any || formParams;
        }
        if (numberOfIssuesFrom !== undefined) {
            formParams = formParams.append('numberOfIssuesFrom', <any>numberOfIssuesFrom) as any || formParams;
        }
        if (numberOfIssuesTo !== undefined) {
            formParams = formParams.append('numberOfIssuesTo', <any>numberOfIssuesTo) as any || formParams;
        }
        if (stardateFrom !== undefined) {
            formParams = formParams.append('stardateFrom', <any>stardateFrom) as any || formParams;
        }
        if (stardateTo !== undefined) {
            formParams = formParams.append('stardateTo', <any>stardateTo) as any || formParams;
        }
        if (yearFrom !== undefined) {
            formParams = formParams.append('yearFrom', <any>yearFrom) as any || formParams;
        }
        if (yearTo !== undefined) {
            formParams = formParams.append('yearTo', <any>yearTo) as any || formParams;
        }
        if (miniseries !== undefined) {
            formParams = formParams.append('miniseries', <any>miniseries) as any || formParams;
        }
        if (photonovelSeries !== undefined) {
            formParams = formParams.append('photonovelSeries', <any>photonovelSeries) as any || formParams;
        }

        return this.httpClient.request<ComicSeriesBaseResponse>('post',`${this.basePath}/v1/rest/comicSeries/search`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
