/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ConflictBaseResponse } from '../model/conflictBaseResponse';
import { ConflictFullResponse } from '../model/conflictFullResponse';
import { ConflictV2FullResponse } from '../model/conflictV2FullResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ConflictService {

    protected basePath = 'https://stapi.co/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Retrieval of a single conflict
     * @param uid Conflict unique ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1GetConflict(uid: string, observe?: 'body', reportProgress?: boolean): Observable<ConflictFullResponse>;
    public v1GetConflict(uid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ConflictFullResponse>>;
    public v1GetConflict(uid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ConflictFullResponse>>;
    public v1GetConflict(uid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling v1GetConflict.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (uid !== undefined && uid !== null) {
            queryParameters = queryParameters.set('uid', <any>uid);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ConflictFullResponse>('get',`${this.basePath}/v1/rest/conflict`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Pagination over conflicts
     * @param pageNumber Zero-based page number
     * @param pageSize Page size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1PageConflicts(pageNumber?: number, pageSize?: number, observe?: 'body', reportProgress?: boolean): Observable<ConflictBaseResponse>;
    public v1PageConflicts(pageNumber?: number, pageSize?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ConflictBaseResponse>>;
    public v1PageConflicts(pageNumber?: number, pageSize?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ConflictBaseResponse>>;
    public v1PageConflicts(pageNumber?: number, pageSize?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ConflictBaseResponse>('get',`${this.basePath}/v1/rest/conflict/search`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Searching conflicts
     * @param name 
     * @param yearFrom 
     * @param yearTo 
     * @param earthConflict 
     * @param federationWar 
     * @param klingonWar 
     * @param dominionWarBattle 
     * @param alternateReality 
     * @param pageNumber Zero-based page number
     * @param pageSize Page size
     * @param sort Sorting, serialized like this: fieldName,ASC;anotherFieldName,DESC
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1SearchConflictsForm(name?: string, yearFrom?: number, yearTo?: number, earthConflict?: boolean, federationWar?: boolean, klingonWar?: boolean, dominionWarBattle?: boolean, alternateReality?: boolean, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'body', reportProgress?: boolean): Observable<ConflictBaseResponse>;
    public v1SearchConflictsForm(name?: string, yearFrom?: number, yearTo?: number, earthConflict?: boolean, federationWar?: boolean, klingonWar?: boolean, dominionWarBattle?: boolean, alternateReality?: boolean, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ConflictBaseResponse>>;
    public v1SearchConflictsForm(name?: string, yearFrom?: number, yearTo?: number, earthConflict?: boolean, federationWar?: boolean, klingonWar?: boolean, dominionWarBattle?: boolean, alternateReality?: boolean, pageNumber?: number, pageSize?: number, sort?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ConflictBaseResponse>>;
    public v1SearchConflictsForm(name?: string, yearFrom?: number, yearTo?: number, earthConflict?: boolean, federationWar?: boolean, klingonWar?: boolean, dominionWarBattle?: boolean, alternateReality?: boolean, pageNumber?: number, pageSize?: number, sort?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {












        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('pageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (name !== undefined) {
            formParams = formParams.append('name', <any>name) as any || formParams;
        }
        if (yearFrom !== undefined) {
            formParams = formParams.append('yearFrom', <any>yearFrom) as any || formParams;
        }
        if (yearTo !== undefined) {
            formParams = formParams.append('yearTo', <any>yearTo) as any || formParams;
        }
        if (earthConflict !== undefined) {
            formParams = formParams.append('earthConflict', <any>earthConflict) as any || formParams;
        }
        if (federationWar !== undefined) {
            formParams = formParams.append('federationWar', <any>federationWar) as any || formParams;
        }
        if (klingonWar !== undefined) {
            formParams = formParams.append('klingonWar', <any>klingonWar) as any || formParams;
        }
        if (dominionWarBattle !== undefined) {
            formParams = formParams.append('dominionWarBattle', <any>dominionWarBattle) as any || formParams;
        }
        if (alternateReality !== undefined) {
            formParams = formParams.append('alternateReality', <any>alternateReality) as any || formParams;
        }

        return this.httpClient.request<ConflictBaseResponse>('post',`${this.basePath}/v1/rest/conflict/search`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Retrieval of a single conflict (V2)
     * @param uid Conflict unique ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2GetConflict(uid: string, observe?: 'body', reportProgress?: boolean): Observable<ConflictV2FullResponse>;
    public v2GetConflict(uid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ConflictV2FullResponse>>;
    public v2GetConflict(uid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ConflictV2FullResponse>>;
    public v2GetConflict(uid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling v2GetConflict.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (uid !== undefined && uid !== null) {
            queryParameters = queryParameters.set('uid', <any>uid);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ConflictV2FullResponse>('get',`${this.basePath}/v2/rest/conflict`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
