/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Full animal, returned when queried using UID
 */
export interface AnimalFull { 
    /**
     * Animal unique ID
     */
    uid: string;
    /**
     * Animal name
     */
    name: string;
    /**
     * Whether it's an earth animal
     */
    earthAnimal?: boolean;
    /**
     * Whether it's an earth insect
     */
    earthInsect?: boolean;
    /**
     * Whether it's an avian
     */
    avian?: boolean;
    /**
     * Whether it's a canine
     */
    canine?: boolean;
    /**
     * Whether it's a feline
     */
    feline?: boolean;
}