/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Astronomical object type (V2)
 */
export type AstronomicalObjectV2Type = 'PLANET' | 'D_CLASS_PLANET' | 'H_CLASS_PLANET' | 'GAS_GIANT_PLANET' | 'K_CLASS_PLANET' | 'L_CLASS_PLANET' | 'M_CLASS_PLANET' | 'Y_CLASS_PLANET' | 'ROGUE_PLANET' | 'ARTIFICIAL_PLANET' | 'ASTEROID' | 'ASTEROIDAL_MOON' | 'ASTEROID_BELT' | 'BORG_SPATIAL_DESIGNATION' | 'CLUSTER' | 'COMET' | 'CONSTELLATION' | 'GALAXY' | 'MOON' | 'M_CLASS_MOON' | 'NEBULA' | 'PLANETOID' | 'D_CLASS_PLANETOID' | 'QUADRANT' | 'QUASAR' | 'STAR' | 'STAR_SYSTEM' | 'SECTOR' | 'REGION';

export const AstronomicalObjectV2Type = {
    PLANET: 'PLANET' as AstronomicalObjectV2Type,
    DCLASSPLANET: 'D_CLASS_PLANET' as AstronomicalObjectV2Type,
    HCLASSPLANET: 'H_CLASS_PLANET' as AstronomicalObjectV2Type,
    GASGIANTPLANET: 'GAS_GIANT_PLANET' as AstronomicalObjectV2Type,
    KCLASSPLANET: 'K_CLASS_PLANET' as AstronomicalObjectV2Type,
    LCLASSPLANET: 'L_CLASS_PLANET' as AstronomicalObjectV2Type,
    MCLASSPLANET: 'M_CLASS_PLANET' as AstronomicalObjectV2Type,
    YCLASSPLANET: 'Y_CLASS_PLANET' as AstronomicalObjectV2Type,
    ROGUEPLANET: 'ROGUE_PLANET' as AstronomicalObjectV2Type,
    ARTIFICIALPLANET: 'ARTIFICIAL_PLANET' as AstronomicalObjectV2Type,
    ASTEROID: 'ASTEROID' as AstronomicalObjectV2Type,
    ASTEROIDALMOON: 'ASTEROIDAL_MOON' as AstronomicalObjectV2Type,
    ASTEROIDBELT: 'ASTEROID_BELT' as AstronomicalObjectV2Type,
    BORGSPATIALDESIGNATION: 'BORG_SPATIAL_DESIGNATION' as AstronomicalObjectV2Type,
    CLUSTER: 'CLUSTER' as AstronomicalObjectV2Type,
    COMET: 'COMET' as AstronomicalObjectV2Type,
    CONSTELLATION: 'CONSTELLATION' as AstronomicalObjectV2Type,
    GALAXY: 'GALAXY' as AstronomicalObjectV2Type,
    MOON: 'MOON' as AstronomicalObjectV2Type,
    MCLASSMOON: 'M_CLASS_MOON' as AstronomicalObjectV2Type,
    NEBULA: 'NEBULA' as AstronomicalObjectV2Type,
    PLANETOID: 'PLANETOID' as AstronomicalObjectV2Type,
    DCLASSPLANETOID: 'D_CLASS_PLANETOID' as AstronomicalObjectV2Type,
    QUADRANT: 'QUADRANT' as AstronomicalObjectV2Type,
    QUASAR: 'QUASAR' as AstronomicalObjectV2Type,
    STAR: 'STAR' as AstronomicalObjectV2Type,
    STARSYSTEM: 'STAR_SYSTEM' as AstronomicalObjectV2Type,
    SECTOR: 'SECTOR' as AstronomicalObjectV2Type,
    REGION: 'REGION' as AstronomicalObjectV2Type
};