/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AstronomicalObjectV2Full } from './astronomicalObjectV2Full';

/**
 * Response object for single astronomical object query (V2)
 */
export interface AstronomicalObjectV2FullResponse { 
    astronomicalObject?: AstronomicalObjectV2Full;
}