/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AstronomicalObjectBase } from './astronomicalObjectBase';
import { AstronomicalObjectType } from './astronomicalObjectType';

/**
 * Full astronomical object, returned when queried using UID
 */
export interface AstronomicalObjectFull { 
    /**
     * Astronomical object's unique ID
     */
    uid: string;
    /**
     * Astronomical object name
     */
    name: string;
    astronomicalObjectType?: AstronomicalObjectType;
    location?: AstronomicalObjectBase;
    /**
     * Astronomical objects located in this astronomical object, like planets in a star system
     */
    astronomicalObjects: Array<AstronomicalObjectBase>;
}