/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AstronomicalObjectBase } from './astronomicalObjectBase';
import { ResponsePage } from './responsePage';
import { ResponseSort } from './responseSort';

/**
 * Response object for astronomical objects search
 */
export interface AstronomicalObjectBaseResponse { 
    page?: ResponsePage;
    sort?: ResponseSort;
    astronomicalObjects?: Array<AstronomicalObjectBase>;
}