/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Blood type
 */
export type BloodType = 'B_NEGATIVE' | 'O_NEGATIVE' | 'T_NEGATIVE';

export const BloodType = {
    BNEGATIVE: 'B_NEGATIVE' as BloodType,
    ONEGATIVE: 'O_NEGATIVE' as BloodType,
    TNEGATIVE: 'T_NEGATIVE' as BloodType
};