/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BookV2Full } from './bookV2Full';

/**
 * Response object for single book query (V2)
 */
export interface BookV2FullResponse { 
    book?: BookV2Full;
}