/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BookBase } from './bookBase';
import { ResponsePage } from './responsePage';
import { ResponseSort } from './responseSort';

/**
 * Response object for books search
 */
export interface BookBaseResponse { 
    page?: ResponsePage;
    sort?: ResponseSort;
    /**
     * List of books matching given criteria
     */
    books?: Array<BookBase>;
}