/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BookCollectionBase } from './bookCollectionBase';
import { ResponsePage } from './responsePage';
import { ResponseSort } from './responseSort';

/**
 * Response object for book collections search
 */
export interface BookCollectionBaseResponse { 
    page?: ResponsePage;
    sort?: ResponseSort;
    /**
     * List of book collections matching given criteria
     */
    bookCollections?: Array<BookCollectionBase>;
}