/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RequestSort } from './requestSort';

/**
 * Comic series search criteria
 */
export interface ComicSeriesSearchCriteria { 
    /**
     * Zero-based page number
     */
    pageNumber?: number;
    /**
     * Page size
     */
    pageSize?: number;
    sort?: RequestSort;
    /**
     * Comic series title
     */
    title?: string;
    /**
     * Starting year the comic series was published
     */
    publishedYearFrom?: number;
    /**
     * Ending year the comic series was published
     */
    publishedYearTo?: number;
    /**
     * Minimal number of issues
     */
    numberOfIssuesFrom?: number;
    /**
     * Maximal number of issues
     */
    numberOfIssuesTo?: number;
    /**
     * Starting stardate of comic series stories
     */
    stardateFrom?: number;
    /**
     * Starting stardate of comic series stories
     */
    stardateTo?: number;
    /**
     * Starting year of comic series stories
     */
    yearFrom?: number;
    /**
     * Ending year of comic series stories
     */
    yearTo?: number;
    /**
     * Whether it should be a miniseries
     */
    miniseries?: boolean;
    /**
     * Whether it should be photonovel series
     */
    photonovelSeries?: boolean;
}