/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ComicCollectionV2Full } from './comicCollectionV2Full';

/**
 * Response object for single comic collection query (V2)
 */
export interface ComicCollectionV2FullResponse { 
    comicCollection?: ComicCollectionV2Full;
}