/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RequestSort } from './requestSort';

/**
 * Comic strip search criteria
 */
export interface ComicStripSearchCriteria { 
    /**
     * Zero-based page number
     */
    pageNumber?: number;
    /**
     * Page size
     */
    pageSize?: number;
    sort?: RequestSort;
    /**
     * Comic strip title
     */
    title?: string;
    /**
     * Starting year the comic strip was published
     */
    publishedYearFrom?: number;
    /**
     * Ending year the comic strip was published
     */
    publishedYearTo?: number;
    /**
     * Minimal number of pages
     */
    numberOfPagesFrom?: number;
    /**
     * Maximal number of pages
     */
    numberOfPagesTo?: number;
    /**
     * Starting year of comic strip story
     */
    yearFrom?: number;
    /**
     * Ending year of comic strip story
     */
    yearTo?: number;
}