/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CharacterBase } from './characterBase';
import { ComicCollectionBase } from './comicCollectionBase';
import { ComicSeriesBase } from './comicSeriesBase';
import { CompanyBase } from './companyBase';
import { Reference } from './reference';
import { StaffBase } from './staffBase';

/**
 * Full comics, returned when queried using UID
 */
export interface ComicsFull { 
    /**
     * Comics unique ID
     */
    uid: string;
    /**
     * Comics title
     */
    title: string;
    /**
     * Year the comics was published
     */
    publishedYear?: number;
    /**
     * Month the comics was published
     */
    publishedMonth?: number;
    /**
     * Day the comics was published
     */
    publishedDay?: number;
    /**
     * Cover publication year
     */
    coverYear?: number;
    /**
     * Cover publication month
     */
    coverMonth?: number;
    /**
     * Cover publication day
     */
    coverDay?: number;
    /**
     * Number of pages
     */
    numberOfPages?: number;
    /**
     * Starting stardate of comic story
     */
    stardateFrom?: number;
    /**
     * Ending stardate of comic story
     */
    stardateTo?: number;
    /**
     * Starting year of comic  story
     */
    yearFrom?: number;
    /**
     * Ending year of comic story
     */
    yearTo?: number;
    /**
     * Whether it's a photonovel
     */
    photonovel?: boolean;
    /**
     * Whether it's an adaptation of an episode or a movie
     */
    adaptation?: boolean;
    /**
     * Comic series this comics is included in
     */
    comicSeries?: Array<ComicSeriesBase>;
    /**
     * Writers involved in the comics
     */
    writers?: Array<StaffBase>;
    /**
     * Artists involved in the comics
     */
    artists?: Array<StaffBase>;
    /**
     * Editors involved in the comics
     */
    editors?: Array<StaffBase>;
    /**
     * Other staff involved in the comics
     */
    staff?: Array<StaffBase>;
    /**
     * Comics publishers
     */
    publishers?: Array<CompanyBase>;
    /**
     * Characters appearing in the comics
     */
    characters?: Array<CharacterBase>;
    /**
     * References
     */
    references?: Array<Reference>;
    /**
     * Comic collections this comics is included in
     */
    comicCollections?: Array<ComicCollectionBase>;
}