/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ComicCollectionBase } from './comicCollectionBase';
import { ResponsePage } from './responsePage';
import { ResponseSort } from './responseSort';

/**
 * Response object for comic collections search
 */
export interface ComicCollectionBaseResponse { 
    page?: ResponsePage;
    sort?: ResponseSort;
    /**
     * List of comic collections matching given criteria
     */
    comicCollections?: Array<ComicCollectionBase>;
}