/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ComicCollectionSearchBody { 
    /**
     * Comic collection title
     */
    title?: string;
    /**
     * Starting year the comic collection was published
     */
    publishedYearFrom?: number;
    /**
     * Ending year the comic collection was published
     */
    publishedYearTo?: number;
    /**
     * Minimal number of pages
     */
    numberOfPagesFrom?: number;
    /**
     * Maximal number of pages
     */
    numberOfPagesTo?: number;
    /**
     * Starting stardate of comic collection stories
     */
    stardateFrom?: number;
    /**
     * Ending stardate of comic collections stories
     */
    stardateTo?: number;
    /**
     * Starting year of comic collection stories
     */
    yearFrom?: number;
    /**
     * Ending year of comic collections stories
     */
    yearTo?: number;
    /**
     * Whether it should be an photonovel collection
     */
    photonovel?: boolean;
}