/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompanyV2Base } from './companyV2Base';
import { ResponsePage } from './responsePage';
import { ResponseSort } from './responseSort';

/**
 * Response object for companies search (V2)
 */
export interface CompanyV2BaseResponse { 
    page?: ResponsePage;
    sort?: ResponseSort;
    /**
     * List of companies matching given criteria
     */
    companies?: Array<CompanyV2Base>;
}