/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Content langauge
 */
export interface ContentLanguage { 
    /**
     * Language unique ID
     */
    uid?: string;
    /**
     * Language name
     */
    name?: string;
    /**
     * ISO 639-1 code
     */
    iso6391Code?: string;
}