/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Real-world country
 */
export interface Country { 
    /**
     * Country unique ID
     */
    uid?: string;
    /**
     * Country name
     */
    name?: string;
    /**
     * ISO 3166-1 alpha-2 code
     */
    iso31661Alpha2Code?: string;
}