/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FoodBase } from './foodBase';
import { ResponsePage } from './responsePage';
import { ResponseSort } from './responseSort';

/**
 * Response object for foods search
 */
export interface FoodBaseResponse { 
    page?: ResponsePage;
    sort?: ResponseSort;
    /**
     * List of foods matching given criteria
     */
    foods?: Array<FoodBase>;
}