/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompanyBase } from './companyBase';
import { MagazineSeriesBase } from './magazineSeriesBase';
import { StaffBase } from './staffBase';

/**
 * Full magazine, returned when queried using UID
 */
export interface MagazineFull { 
    /**
     * Magazine unique ID
     */
    uid: string;
    /**
     * Magazine title
     */
    title: string;
    /**
     * Year the magazine was published
     */
    publishedYear?: number;
    /**
     * Month the magazine was published
     */
    publishedMonth?: number;
    /**
     * Day the magazine was published
     */
    publishedDay?: number;
    /**
     * Cover publication year
     */
    coverYear?: number;
    /**
     * Cover publication month
     */
    coverMonth?: number;
    /**
     * Cover publication day
     */
    coverDay?: number;
    /**
     * Number of pages
     */
    numberOfPages?: number;
    /**
     * Magazine issue number
     */
    issueNumber?: string;
    /**
     * Magazine series this magazine is included in
     */
    magazineSeries?: Array<MagazineSeriesBase>;
    /**
     * Editors involved in the magazine
     */
    editors?: Array<StaffBase>;
    /**
     * Magazine publishers
     */
    publishers?: Array<CompanyBase>;
}