/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Base magazine series, returned in search results
 */
export interface MagazineSeriesBase { 
    /**
     * Magazine series unique ID
     */
    uid: string;
    /**
     * Magazine series title
     */
    title: string;
    /**
     * Year from which the magazine series was published
     */
    publishedYearFrom?: number;
    /**
     * Month from which the magazine series was published
     */
    publishedMonthFrom?: number;
    /**
     * Year to which the magazine series was published
     */
    publishedYearTo?: number;
    /**
     * Month to which the magazine series was published
     */
    publishedMonthTo?: number;
    /**
     * Number of issues
     */
    numberOfIssues?: number;
}