/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Base material, returned in search results
 */
export interface MaterialBase { 
    /**
     * Material unique ID
     */
    uid: string;
    /**
     * Material name
     */
    name: string;
    /**
     * Whether it's a chemical compound
     */
    chemicalCompound?: boolean;
    /**
     * Whether it's a biochemical compound
     */
    biochemicalCompound?: boolean;
    /**
     * Whether it's a drug
     */
    drug?: boolean;
    /**
     * Whether it's a poisonous substance
     */
    poisonousSubstance?: boolean;
    /**
     * Whether it's an explosive
     */
    explosive?: boolean;
    /**
     * Whether it's a gemstone
     */
    gemstone?: boolean;
    /**
     * Whether it's an alloy or a composite
     */
    alloyOrComposite?: boolean;
    /**
     * Whether it's a fuel
     */
    fuel?: boolean;
    /**
     * Whether it's a mineral
     */
    mineral?: boolean;
    /**
     * Whether it's a precious material
     */
    preciousMaterial?: boolean;
}