/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object describing response page
 */
export interface ResponsePage { 
    /**
     * Zero-based page number
     */
    pageNumber?: number;
    /**
     * Page size
     */
    pageSize?: number;
    /**
     * Number of elements in page
     */
    numberOfElements?: number;
    /**
     * Total elements found
     */
    totalElements?: number;
    /**
     * Total pages found
     */
    totalPages?: number;
    /**
     * Whether it is the first page
     */
    firstPage?: boolean;
    /**
     * Whether it is the last page
     */
    lastPage?: boolean;
}