/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SeasonFull } from './seasonFull';

/**
 * Response object for single season query
 */
export interface SeasonFullResponse { 
    season?: SeasonFull;
}