/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SeriesFull } from './seriesFull';

/**
 * Response object for single series query
 */
export interface SeriesFullResponse { 
    series?: SeriesFull;
}