/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompanyBase } from './companyBase';
import { Reference } from './reference';
import { StaffBase } from './staffBase';

/**
 * Full soundtrack, returned when queried using UID
 */
export interface SoundtrackFull { 
    /**
     * Soundtrack unique ID
     */
    uid: string;
    /**
     * Soundtrack title
     */
    title: string;
    /**
     * Release date
     */
    releaseDate?: string;
    /**
     * Length, in seconds
     */
    length?: number;
    /**
     * Labels this soundtrack was released by
     */
    labels?: Array<CompanyBase>;
    /**
     * Composers
     */
    composers?: Array<StaffBase>;
    /**
     * Other musicians that contributed to this soundtrack
     */
    contributors?: Array<StaffBase>;
    /**
     * Orchestrators
     */
    orchestrators?: Array<StaffBase>;
    /**
     * References
     */
    references?: Array<Reference>;
}