/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrganizationBase } from './organizationBase';
import { SpacecraftClassV2Base } from './spacecraftClassV2Base';
import { SpacecraftType } from './spacecraftType';

/**
 * Full spacecraft, returned when queried using UID (V2)
 */
export interface SpacecraftV2Full { 
    /**
     * Spacecraft unique ID
     */
    uid: string;
    /**
     * Spacecraft name
     */
    name: string;
    /**
     * Spacecraft registry
     */
    registry?: string;
    /**
     * Status of a spacecraft (in prime reality, if spacecraft was in more than one realities)
     */
    status?: string;
    /**
     * Date the spacecraft status was last known
     */
    dateStatus?: string;
    spacecraftClass?: SpacecraftClassV2Base;
    owner?: OrganizationBase;
    operator?: OrganizationBase;
    affiliation?: OrganizationBase;
    /**
     * Spacecraft types
     */
    spacecraftTypes?: Array<SpacecraftType>;
}