/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponsePage } from './responsePage';
import { ResponseSort } from './responseSort';
import { SpacecraftClassBase } from './spacecraftClassBase';

/**
 * Response object for spacecraft classes search
 */
export interface SpacecraftClassBaseResponse { 
    page?: ResponsePage;
    sort?: ResponseSort;
    /**
     * List of spacecraft classes matching given criteria
     */
    spacecraftClasses?: Array<SpacecraftClassBase>;
}