/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SpacecraftV2Full } from './spacecraftV2Full';

/**
 * Response object for single spacecraft query (V2)
 */
export interface SpacecraftV2FullResponse { 
    spacecraft?: SpacecraftV2Full;
}