/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SpeciesV2Full } from './speciesV2Full';

/**
 * Response object for single species query (V2)
 */
export interface SpeciesV2FullResponse { 
    species?: SpeciesV2Full;
}