/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponsePage } from './responsePage';
import { ResponseSort } from './responseSort';
import { TechnologyBase } from './technologyBase';

/**
 * Response object for technology search
 */
export interface TechnologyBaseResponse { 
    page?: ResponsePage;
    sort?: ResponseSort;
    /**
     * List of technology matching given criteria
     */
    technology?: Array<TechnologyBase>;
}