/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TitleV2Full } from './titleV2Full';

/**
 * Response object for single title query (V2)
 */
export interface TitleV2FullResponse { 
    title?: TitleV2Full;
}