/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Base title, returned in search results (V2)
 */
export interface TitleV2Base { 
    /**
     * Title unique ID
     */
    uid: string;
    /**
     * Title name
     */
    name: string;
    /**
     * Whether it's a military rank
     */
    militaryRank?: boolean;
    /**
     * Whether it's a fleet rank
     */
    fleetRank?: boolean;
    /**
     * Whether it's a religious title
     */
    religiousTitle?: boolean;
    /**
     * Whether it's a education title
     */
    educationTitle?: boolean;
    /**
     * Whether this title is from mirror universe
     */
    mirror?: boolean;
}