/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TitleSearchBody1 { 
    /**
     * Title name
     */
    name?: string;
    /**
     * Whether it should be a military rank
     */
    militaryRank?: boolean;
    /**
     * Whether it should be a fleet rank
     */
    fleetRank?: boolean;
    /**
     * Whether it should be a religious title
     */
    religiousTitle?: boolean;
    /**
     * Whether it should be a education title
     */
    educationTitle?: boolean;
    /**
     * Whether this title should be from mirror universe
     */
    mirror?: boolean;
}