/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TradingCardDeckHeader } from './tradingCardDeckHeader';
import { TradingCardSetHeader } from './tradingCardSetHeader';

/**
 * Base trading card, returned in search results
 */
export interface TradingCardBase { 
    /**
     * Trading card unique ID
     */
    uid: string;
    /**
     * Trading card name
     */
    name: string;
    /**
     * Trading card number
     */
    number?: string;
    /**
     * Release year, if set was releases over multiple years
     */
    releaseYear?: number;
    /**
     * Production run, if different from trading card set production run
     */
    productionRun?: number;
    tradingCardSet?: TradingCardSetHeader;
    tradingCardDeck?: TradingCardDeckHeader;
}