/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponsePage } from './responsePage';
import { ResponseSort } from './responseSort';
import { TradingCardDeckBase } from './tradingCardDeckBase';

/**
 * Response object for trading card decks search
 */
export interface TradingCardDeckBaseResponse { 
    page?: ResponsePage;
    sort?: ResponseSort;
    /**
     * List of trading card decks matching given criteria
     */
    tradingCardDecks?: Array<TradingCardDeckBase>;
}