/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Header trading card set, embedded in other objects
 */
export interface TradingCardSetHeader { 
    /**
     * Trading card set unique ID
     */
    uid: string;
    /**
     * Trading card set name
     */
    name: string;
}