/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Video release format
 */
export type VideoReleaseFormat = 'SUPER_8' | 'BETAMAX' | 'VHS' | 'CED' | 'LD' | 'VHD' | 'VCD' | 'VIDEO_8' | 'DVD' | 'UMD' | 'HD_DVD' | 'BLU_RAY' | 'BLU_RAY_4K_UHD' | 'DIGITAL_FORMAT';

export const VideoReleaseFormat = {
    SUPER8: 'SUPER_8' as VideoReleaseFormat,
    BETAMAX: 'BETAMAX' as VideoReleaseFormat,
    VHS: 'VHS' as VideoReleaseFormat,
    CED: 'CED' as VideoReleaseFormat,
    LD: 'LD' as VideoReleaseFormat,
    VHD: 'VHD' as VideoReleaseFormat,
    VCD: 'VCD' as VideoReleaseFormat,
    VIDEO8: 'VIDEO_8' as VideoReleaseFormat,
    DVD: 'DVD' as VideoReleaseFormat,
    UMD: 'UMD' as VideoReleaseFormat,
    HDDVD: 'HD_DVD' as VideoReleaseFormat,
    BLURAY: 'BLU_RAY' as VideoReleaseFormat,
    BLURAY4KUHD: 'BLU_RAY_4K_UHD' as VideoReleaseFormat,
    DIGITALFORMAT: 'DIGITAL_FORMAT' as VideoReleaseFormat
};