/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponsePage } from './responsePage';
import { ResponseSort } from './responseSort';
import { VideoReleaseV2Base } from './videoReleaseV2Base';

/**
 * Response object for video releases search (V2)
 */
export interface VideoReleaseV2BaseResponse { 
    page?: ResponsePage;
    sort?: ResponseSort;
    /**
     * List of video releases matching given criteria
     */
    videoReleases?: Array<VideoReleaseV2Base>;
}