/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RequestSort } from './requestSort';

/**
 * Video release search criteria (V2)
 */
export interface VideoReleaseV2SearchCriteria { 
    /**
     * Zero-based page number
     */
    pageNumber?: number;
    /**
     * Page size
     */
    pageSize?: number;
    sort?: RequestSort;
    /**
     * Video release title
     */
    title?: string;
    /**
     * Starting year of video release story
     */
    yearFrom?: number;
    /**
     * Ending year of video release story
     */
    yearTo?: number;
    /**
     * Minimal run time, in minutes
     */
    runTimeFrom?: number;
    /**
     * Minimal run time, in minutes
     */
    runTimeTo?: number;
    /**
     * Whether it should be a documentary
     */
    documentary?: boolean;
    /**
     * Whether it should contain special features
     */
    specialFeatures?: boolean;
}