/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface WeaponSearchBody { 
    /**
     * Weapon name
     */
    name?: string;
    /**
     * Whether it should be a hand-help weapon
     */
    handHeldWeapon?: boolean;
    /**
     * Whether it should be a laser technology
     */
    laserTechnology?: boolean;
    /**
     * Whether it should be a plasma technology
     */
    plasmaTechnology?: boolean;
    /**
     * Whether it should be a photonic technology
     */
    photonicTechnology?: boolean;
    /**
     * Whether it should be a phaser technology
     */
    phaserTechnology?: boolean;
    /**
     * Whether this weapon should be from mirror universe
     */
    mirror?: boolean;
    /**
     * Whether this weapon should be from alternate reality
     */
    alternateReality?: boolean;
}