/**
 * STAPI
 * STAPI, a Star Trek API
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WeaponV2Full } from './weaponV2Full';

/**
 * Response object for single weapon query (V2)
 */
export interface WeaponV2FullResponse { 
    weapon?: WeaponV2Full;
}